In [43]:
import numpy as np
from numpy.linalg import norm

In [13]:
def F(point,A,B):
    return point.transpose() * A * point +  2 * B.transpose() * point

def Gradient(point , A, B):
    return 2 * A * point + 2*B

$$ proj_{box}(x) = [ \max(l_i, \min(x_i, u_i))]  \quad \forall i  $$


In [14]:
def projection_to_box(constrains , point):
    res = point[:]
    for i in range(len(point)):
        if(int(point[i]) < constrains[i][0]):
            res[i] = constrains[i][0]
        if(int(point[i]) > constrains[i][1]):
            res[i] = constrains[i][1]
    return res

$$proj_{ball}(x) = c + min(r, ||x - c||) * \frac {(x - c)}{ ||x - c||}  $$

In [15]:
def projection_to_ball(point, c, r):
    return c + min( r, norm(point-c)) * (point-c)/norm(point-c) 

$$ proj_{R_{++}}(x) = [max(x_i, 0)] \quad  \forall i $$

In [35]:
def projection_to_positive(point):
    for i in range(len(point)):
        point[i] = max(point[i],0)
    return point

# The Gradient Projection Method

**Input:** ε > 0 - tolerance parameter.

**Initialization:** Pick x₀ ∈ C arbitrarily.

**General step:** For any k = 0, 1, 2, ... execute the following steps:
- Pick a stepsize tₖ by a line search procedure.
- Set xₖ₊₁ = PC(xₖ - tₖ∇f(xₖ)).
- If ∥xₖ - xₖ₊₁∥ ≤ ε, then STOP, and xₖ₊₁ is the output.


$$ f(x,y,z) = x^2 + y^3 + z^4 + 2xy - 3xz -4x -2y $$

In [17]:
A = np.matrix([[2,2,0],[0,3,0],[-3,0,4]])
B = np.matrix([-4,-2,-1]).transpose()


$$ Box: [-5,15] * [-10,-3] * [-20,60] $$

In [18]:
constrains = [(5,15),(-10,-3),[-20,60]]
point = np.matrix([10,-2,30]).transpose()
temp = np.matrix([5,-10,40]).transpose()
while norm(point-temp)>1e-5:
    temp = point
    point = projection_to_box(constrains,point - Gradient(point,A,B) * 0.2)
F(point,A,B)

matrix([[15.00005472]])

$$Ball(c = (10,10,10) ,r = 5)$$

In [19]:
r = 5
c = np.matrix([10,10,10]).transpose()
point = np.matrix([10,10,10]).transpose()
temp = np.matrix([5,8,60]).transpose()
while norm(point-temp)>1e-5:
    temp = point
    point = projection_to_ball(point - Gradient(point,A,B) * 0.2,c,r)
F(point,A,B)

matrix([[332.92420722]])

$$ \R^3_+ $$

In [38]:
point = np.matrix([20,2,3]).transpose()
temp = np.matrix([5,8,60]).transpose()
while norm(point-temp)>1e-5:
    temp = point
    point = projection_to_positive(point - Gradient(point,A,B) * 0.2)
F(point,A,B)


matrix([[-7.91665631]])